name: Elixir CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['22.2']
        elixir: ['1.11', '1.12', '1.13']
        include:
          - otp: '20.3'
            elixir: '1.9'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Check formatter 
        run: mix format --check-formatted
      - name: Run Tests
        run: mix test
